// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/paologallinaharbur/usersmanager/models"
)

// GetUserAcceptedCode is the HTTP code returned for type GetUserAccepted
const GetUserAcceptedCode int = 202

/*GetUserAccepted OK

swagger:response getUserAccepted
*/
type GetUserAccepted struct {

	/*
	  In: Body
	*/
	Payload models.UserDataList `json:"body,omitempty"`
}

// NewGetUserAccepted creates GetUserAccepted with default headers values
func NewGetUserAccepted() *GetUserAccepted {

	return &GetUserAccepted{}
}

// WithPayload adds the payload to the get user accepted response
func (o *GetUserAccepted) WithPayload(payload models.UserDataList) *GetUserAccepted {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user accepted response
func (o *GetUserAccepted) SetPayload(payload models.UserDataList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(202)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.UserDataList{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetUserBadRequestCode is the HTTP code returned for type GetUserBadRequest
const GetUserBadRequestCode int = 400

/*GetUserBadRequest bad request

swagger:response getUserBadRequest
*/
type GetUserBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetUserBadRequest creates GetUserBadRequest with default headers values
func NewGetUserBadRequest() *GetUserBadRequest {

	return &GetUserBadRequest{}
}

// WithPayload adds the payload to the get user bad request response
func (o *GetUserBadRequest) WithPayload(payload *models.Error) *GetUserBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user bad request response
func (o *GetUserBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUserInternalServerErrorCode is the HTTP code returned for type GetUserInternalServerError
const GetUserInternalServerErrorCode int = 500

/*GetUserInternalServerError internal server error

swagger:response getUserInternalServerError
*/
type GetUserInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetUserInternalServerError creates GetUserInternalServerError with default headers values
func NewGetUserInternalServerError() *GetUserInternalServerError {

	return &GetUserInternalServerError{}
}

// WithPayload adds the payload to the get user internal server error response
func (o *GetUserInternalServerError) WithPayload(payload *models.Error) *GetUserInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user internal server error response
func (o *GetUserInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
