// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UserID user Id
//
// swagger:model userId
type UserID struct {

	// nickName
	// Required: true
	NickName *string `json:"nickName"`
}

// Validate validates this user Id
func (m *UserID) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNickName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserID) validateNickName(formats strfmt.Registry) error {

	if err := validate.Required("nickName", "body", m.NickName); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UserID) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserID) UnmarshalBinary(b []byte) error {
	var res UserID
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
